-- CloudVerse / EGSPEC production database
-- Run this once in Supabase SQL Editor.

create table if not exists public.app_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  name text not null,
  gender text,
  category text,
  email text unique not null,
  phone text,
  institution text,
  password_hash text not null,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  created_at timestamptz not null default now()
);

-- Storage bucket for admin-uploaded member/gallery/logo images.
insert into storage.buckets (id, name, public)
values ('site-images', 'site-images', true)
on conflict (id) do update set public = true;

-- The website uses the server-side Supabase service-role key.
-- Do NOT put that key in HTML, JavaScript, or Vercel client-side variables.
